name: terraform test workflow
on:
  pull_request:

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4

      - uses: aquaproj/aqua-installer@v0.6.0
        with:
          aqua_version: v0.10.0

      - uses: suzuki-shunsuke/trivy-config-action@main
        with:
          github_token: ${{github.token}}
          github_comment: 'true'
          config_path: './trivy.yml'

